version: '3.8'

services:
  h2-database:
    image: oscarfonts/h2
    container_name: h2-database
    ports:
      - "8082:8082" # Adjust the port if necessary
    volumes:
      - ./data:/opt/h2-data # Persist data to local directory
    environment:
      - H2_OPTIONS=-ifNotExists
    networks:
      - backend

networks:
  backend:
    driver: bridge
